services:
  app:
    build: .
    container_name: certificados-seberi
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - cert_data:/app/instance
      - cert_certificates:/app/certificates
      - cert_template:/app/template_data
    environment:
      - TZ=America/Sao_Paulo

volumes:
  cert_data:
    name: certificados_seberi_data
  cert_certificates:
    name: certificados_seberi_certificates
  cert_template:
    name: certificados_seberi_template
