services:
  app:
    build: .
    container_name: certificados-seberi
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - ./certificates:/app/certificates
    environment:
      - TZ=America/Sao_Paulo
